const moodProfiles = {
  official: ["landscape", "solid", "balanced", "logo", "logo-watermark", "subtle", false, false, ["tier", "expiryDate"]],
  minimal: ["landscape", "solid", "subtle", "logo", "standard", "subtle", false, false, ["expiryDate"]],
  premium: ["landscape", "gradient", "dominant", "background", "background-emblem", "medium", false, false, ["tier", "loyaltyPoints"]],
  playful: ["portrait", "pattern", "dominant", "hero", "side-emblem", "medium", false, true, ["tier", "decorativeArt"]],
  creative: ["landscape", "image-overlay", "dominant", "hero", "hero-backdrop", "bold", false, true, ["tier", "decorativeArt"]],
  cyberpunk: ["landscape", "gradient", "full", "background", "hero-backdrop", "bold", false, true, ["tier", "decorativeArt"]],
  academic: ["portrait", "solid", "balanced", "logo", "logo-watermark", "medium", true, false, ["photo", "studentId", "course", "expiryDate"]],
  luxury: ["landscape", "gradient", "dominant", "logo", "background-emblem", "bold", false, false, ["tier", "expiryDate"]],
  event: ["portrait", "pattern", "dominant", "hero", "side-emblem", "bold", false, false, ["tier", "email"]],
  identity: ["portrait", "solid", "balanced", "logo", "side-emblem", "subtle", true, false, ["photo", "tier", "expiryDate"]],
};

const intentModifiers = [
  { key: "verification-first", orientation: "landscape", backgroundMode: "solid", colorUsage: "balanced", preferredAsset: "logo", treatment: "standard", intensity: "subtle", usesPhoto: false, usesDecorativeArt: false, fields: ["expiryDate"] },
  { key: "oversized-emblem", orientation: "landscape", backgroundMode: "solid", colorUsage: "dominant", preferredAsset: "logo", treatment: "background-emblem", intensity: "bold", usesPhoto: false, usesDecorativeArt: false, fields: ["tier"] },
  { key: "cinematic-backdrop", orientation: "landscape", backgroundMode: "image-overlay", colorUsage: "full", preferredAsset: "hero", treatment: "hero-backdrop", intensity: "bold", usesPhoto: false, usesDecorativeArt: false, fields: ["tier"] },
  { key: "portrait-identity", orientation: "portrait", backgroundMode: "solid", colorUsage: "balanced", preferredAsset: "logo", treatment: "side-emblem", intensity: "subtle", usesPhoto: true, usesDecorativeArt: false, fields: ["photo", "tier", "expiryDate"] },
  { key: "collectible-art", orientation: "portrait", backgroundMode: "pattern", colorUsage: "full", preferredAsset: "background", treatment: "side-emblem", intensity: "bold", usesPhoto: false, usesDecorativeArt: true, fields: ["tier", "decorativeArt", "dateJoined"] },
  { key: "essential-fields", orientation: "landscape", backgroundMode: "solid", colorUsage: "subtle", preferredAsset: "logo", treatment: "standard", intensity: "subtle", usesPhoto: false, usesDecorativeArt: false, fields: ["expiryDate"], removeFields: ["photo", "decorativeArt", "email", "phone", "course", "loyaltyPoints", "dateJoined"] },
  { key: "rewards-led", orientation: "landscape", backgroundMode: "gradient", colorUsage: "dominant", preferredAsset: "background", treatment: "background-emblem", intensity: "medium", usesPhoto: false, usesDecorativeArt: false, fields: ["tier", "loyaltyPoints"] },
  { key: "lanyard-badge", orientation: "portrait", backgroundMode: "image-overlay", colorUsage: "dominant", preferredAsset: "hero", treatment: "hero-backdrop", intensity: "medium", usesPhoto: true, usesDecorativeArt: false, fields: ["photo", "tier", "email"] },
  { key: "wallet-landscape", orientation: "landscape", backgroundMode: "solid", colorUsage: "balanced", preferredAsset: "logo", treatment: "logo-watermark", intensity: "subtle", usesPhoto: false, usesDecorativeArt: false, fields: ["tier", "expiryDate"] },
  { key: "network-contact", orientation: "landscape", backgroundMode: "solid", colorUsage: "balanced", preferredAsset: "logo", treatment: "side-emblem", intensity: "subtle", usesPhoto: true, usesDecorativeArt: false, fields: ["photo", "tier", "email", "phone"] },
  { key: "immersive-color", orientation: "portrait", backgroundMode: "gradient", colorUsage: "full", preferredAsset: "background", treatment: "background-emblem", intensity: "bold", usesPhoto: false, usesDecorativeArt: false, fields: ["tier"] },
  { key: "quiet-mark", orientation: "landscape", backgroundMode: "solid", colorUsage: "subtle", preferredAsset: "logo", treatment: "logo-watermark", intensity: "subtle", usesPhoto: false, usesDecorativeArt: false, fields: ["tier", "expiryDate"] },
  { key: "pattern-system", orientation: "portrait", backgroundMode: "pattern", colorUsage: "dominant", preferredAsset: "logo", treatment: "side-emblem", intensity: "medium", usesPhoto: false, usesDecorativeArt: true, fields: ["tier", "decorativeArt"] },
  { key: "image-panel", orientation: "landscape", backgroundMode: "image-overlay", colorUsage: "dominant", preferredAsset: "background", treatment: "hero-backdrop", intensity: "medium", usesPhoto: true, usesDecorativeArt: false, fields: ["photo", "tier"] },
  { key: "scan-dominant", orientation: "portrait", backgroundMode: "solid", colorUsage: "balanced", preferredAsset: "logo", treatment: "standard", intensity: "subtle", usesPhoto: false, usesDecorativeArt: false, fields: ["expiryDate"] },
];

const generationPrompts = {
  official: [
    "Design a security-desk credential where verification and expiry can be checked before any decorative detail is noticed.",
    "Turn the organization mark into a confident civic-style seal behind a formal member credential.",
    "Create an official pass that uses the selected hero image like documentary evidence while maintaining sober legibility.",
    "Build a portrait staff ID intended for face-to-face inspection at a controlled entrance.",
    "Create a commemorative official credential with a controlled illustration area that never competes with verification.",
    "Reduce the pass to the few facts a receptionist needs to verify membership quickly.",
    "Design an official benefits credential where status and rewards are visible but never promotional.",
    "Create a tall institutional badge for staff wearing it on a lanyard throughout the day.",
    "Make a compact landscape credential suited to both a wallet screen and an access checkpoint.",
    "Design a professional association ID that doubles as a trusted contact credential.",
    "Use the official color across nearly the whole card while preserving government-form clarity.",
    "Create a restrained credential where a faint institutional mark is the only decorative gesture.",
    "Build a formal patterned security pass inspired by anti-counterfeit document graphics.",
    "Use a documentary image panel beside a precise official identity block.",
    "Design a scan-first official credential for a high-throughput verification queue.",
  ],
  minimal: [
    "Create a verification pass reduced to one calm hierarchy, one scan action, and no visual noise.",
    "Use the logo as a single oversized geometric gesture in an otherwise sparse composition.",
    "Let one quiet brand photograph fill the card while the essential details remain almost editorial.",
    "Design a minimal portrait identity card with the member photo treated like a clean publication portrait.",
    "Create a collectible-looking pass using only one small art detail and a great deal of empty space.",
    "Strip the membership card down to the minimum information needed for it to remain useful.",
    "Make a quiet loyalty card where tier and points feel like carefully typeset facts.",
    "Design a minimal vertical badge with disciplined alignment and an unobtrusive member portrait.",
    "Create a thin, horizontal digital-wallet pass with exceptionally low information density.",
    "Make a minimalist professional contact card that still reads unmistakably as membership.",
    "Use a full field of brand color with almost no decoration and extremely clear typography.",
    "Treat a faint logo watermark as the only brand signal on a nearly monochrome pass.",
    "Create a restrained repeating pattern that is visible only on close inspection.",
    "Use a single cropped image panel balanced by a sparse member-information column.",
    "Make a QR-led minimal pass where every other element quietly supports the scan action.",
  ],
  premium: [
    "Design a concierge-ready premium credential with immediate verification and an understated status signal.",
    "Use the logo as a large embossed-feeling emblem behind an invitation-only membership card.",
    "Create a cinematic premium pass where the selected brand image feels like a private-club interior.",
    "Build a portrait premium identity card that treats the member photograph like an editorial cover.",
    "Design a collectible patron card with a tasteful artwork area and visible membership history.",
    "Create a low-density premium credential where every remaining field feels intentionally placed.",
    "Make tier and loyalty points the centerpiece of a sophisticated rewards membership.",
    "Design a tall VIP badge for a premium hospitality experience with polished member identification.",
    "Create a landscape wallet pass that feels like a high-end physical card translated to screen.",
    "Build a premium networking credential with a portrait and discreet contact information.",
    "Immerse the entire card in the official brand color with a refined tonal hierarchy.",
    "Create a quiet premium card where a subtle watermark communicates more than decoration would.",
    "Use a bespoke-feeling pattern to give the membership card a signature luxury surface.",
    "Design a split visual card with a refined image panel and a precise benefits hierarchy.",
    "Create a premium scan credential where the QR feels integrated rather than technically appended.",
  ],
  playful: [
    "Create a cheerful verification pass that makes routine scanning feel welcoming rather than bureaucratic.",
    "Turn the logo into an oversized playful shape that frames the member details.",
    "Use the hero image as a colorful scene behind a friendly community membership card.",
    "Design a portrait member card where the photo feels like a bright social profile.",
    "Make a collectible character card with a prominent decorative-art slot and join date.",
    "Create a simple friendly pass with only the details members actually use.",
    "Design a rewards card that celebrates points and tier like progress in a game.",
    "Build a vertical community badge with a lively portrait and clear entry code.",
    "Make a horizontal wallet pass that feels energetic even at a small screen size.",
    "Create a friendly networking card with member photo, email, and phone presented conversationally.",
    "Let the official color flood the design in a joyful but still readable way.",
    "Use a soft logo watermark to create a playful surprise without clutter.",
    "Create a bold repeating pattern that feels like branded wrapping paper for membership.",
    "Use a bright image panel beside a compact and approachable member profile.",
    "Design a playful scan-first pass with a QR zone that feels like part of the visual rhythm.",
  ],
  creative: [
    "Design an art-directed verification credential where utility is framed by an unconventional composition.",
    "Transform the logo into an oversized poster-like emblem that becomes the card's main graphic.",
    "Use the selected hero image as a full cinematic canvas for an expressive membership pass.",
    "Create a portrait identity card inspired by an independent magazine cover.",
    "Build a collectible artist card with a dominant custom-art area and visible membership provenance.",
    "Make an experimental but sparse pass using only the essential identity and verification fields.",
    "Turn loyalty status and points into a bold typographic composition.",
    "Design a tall creative-event badge that feels like a limited-edition print.",
    "Create a horizontal wallet card with an asymmetric editorial layout.",
    "Build a creative professional identity card that combines portrait and contact details like a portfolio cover.",
    "Use the primary color as a full-bleed expressive field with assertive type.",
    "Create a subtle conceptual card where the logo appears as a barely visible background artifact.",
    "Develop a distinctive pattern system that could extend across an entire membership program.",
    "Compose a strong image panel against an unexpected but readable information hierarchy.",
    "Make the scan code the visual anchor of an otherwise expressive access card.",
  ],
  cyberpunk: [
    "Create a secure digital credential designed for rapid verification in a neon-lit venue.",
    "Turn the logo into a giant illuminated system emblem behind the access data.",
    "Use the hero image as a high-contrast futuristic city-like backdrop.",
    "Design a portrait identity token with a prominent member photo and technical status readout.",
    "Build a collectible digital-character pass with a bold art slot and membership history.",
    "Create a stripped-back access token containing only critical identity and scan data.",
    "Present loyalty tier and points like live system statistics on a premium digital token.",
    "Design a tall cyberpunk event badge intended for a lanyard and checkpoint scanning.",
    "Create a landscape wallet token with a compact heads-up-display hierarchy.",
    "Make a futuristic professional identity credential with direct contact channels.",
    "Flood the pass with the primary color and sharp high-contrast information layers.",
    "Use the logo as a faint holographic watermark on a controlled technical surface.",
    "Create a coded repeating pattern that suggests encrypted membership data.",
    "Use a dramatic image panel next to a precise digital identity readout.",
    "Design a QR-dominant access token where scanning feels like the central interaction.",
  ],
  academic: [
    "Design a campus verification credential optimized for library, exam, and building checks.",
    "Use the university mark as a large heraldic emblem behind student information.",
    "Create an academic pass with a campus hero image treated like an institutional backdrop.",
    "Build a portrait student ID with photo, student number, course, and expiry clearly prioritized.",
    "Design a collectible alumni or society card with a tasteful decorative-art area.",
    "Create a sparse academic credential showing only the facts required for campus verification.",
    "Make an academic benefits card where status and available points are easy to understand.",
    "Design a tall conference-style academic badge with photo and institutional hierarchy.",
    "Create a landscape student wallet pass for quick everyday campus use.",
    "Build an academic networking credential with portrait and professional contact details.",
    "Use the institutional primary color boldly while retaining formal academic authority.",
    "Create a heritage-inspired academic pass with a subtle crest-like watermark.",
    "Develop a restrained scholarly pattern inspired by archive labels or library grids.",
    "Use a campus image panel beside a formal student identity block.",
    "Design a scan-first academic credential for fast controlled entry during exams.",
  ],
  luxury: [
    "Design a discreet verification credential for an invitation-only membership experience.",
    "Turn the logo into a monumental embossed-style emblem with very restrained supporting detail.",
    "Use a selected brand image like an editorial luxury campaign behind the membership information.",
    "Create a portrait identity card with a member photograph treated like a private-client profile.",
    "Design a collectible patron credential with a carefully framed artwork area.",
    "Reduce the luxury card to essential information and immaculate spacing.",
    "Make membership tier and rewards feel like discreet privileges rather than promotional points.",
    "Create a tall VIP badge for an exclusive event or hospitality setting.",
    "Design a landscape wallet pass that resembles a precision-crafted physical membership card.",
    "Build an elegant private-network credential with photo and subtle contact details.",
    "Use full official color with tonal depth instead of obvious decorative effects.",
    "Create a quiet luxury pass centered on an almost invisible logo watermark.",
    "Develop a refined repeating pattern inspired by bespoke material or engraving.",
    "Use a premium image panel beside a disciplined, high-contrast member hierarchy.",
    "Design a scan-focused luxury credential where the QR remains elegant and easy to use.",
  ],
  event: [
    "Create an access credential optimized for the fastest possible entry-lane verification.",
    "Turn the event mark into a giant stage-like emblem behind attendee details.",
    "Use the hero image as a full event-poster backdrop while keeping attendee data readable.",
    "Design a portrait attendee badge with a highly visible photo for staff inspection.",
    "Build a collectible festival pass with a dedicated artwork area and attendance date.",
    "Create a compact event pass containing only the facts needed at the entrance.",
    "Design a sponsor or VIP event credential where tier and benefits are immediately visible.",
    "Make a tall lanyard badge with photo, attendee tier, contact detail, and a clear QR.",
    "Create a landscape mobile ticket that remains energetic and scannable on a phone.",
    "Build a networking-conference badge with portrait, email, and phone details.",
    "Use the event color as an immersive full-card signal visible from a distance.",
    "Create a restrained event badge using a faint logo watermark and precise information.",
    "Develop a rhythmic pattern that makes multiple attendee badges feel like one event system.",
    "Use a strong event image panel beside compact attendee and access information.",
    "Design a QR-dominant event pass for high-volume gate scanning.",
  ],
  identity: [
    "Create an identity credential where a verifier can confirm membership status in a single glance.",
    "Use the logo as a large supporting emblem that frames, but never competes with, the member.",
    "Place the member identity over a cinematic brand-image backdrop while keeping the face inspectable.",
    "Design a portrait-first identity card with a confident member photograph and formal details.",
    "Build a collectible identity card that pairs the member with a personal decorative-art slot.",
    "Create a sparse identity credential showing only face, name, member ID, expiry, and QR.",
    "Design a member-status identity card that also makes tier and points easy to see.",
    "Create a tall wearable identity badge intended for repeated visual inspection.",
    "Build a landscape identity pass that works naturally in a phone wallet.",
    "Design a professional member identity card with portrait, email, and phone.",
    "Use the primary color across the full identity card without reducing face or text clarity.",
    "Create a restrained identity credential using a quiet logo watermark behind the member.",
    "Develop a branded pattern that surrounds a clear central portrait and identity block.",
    "Use a brand image panel beside a sharply organized member portrait and details.",
    "Design a scan-first identity credential with the QR and portrait treated as equal verification tools.",
  ],
};

const refinementPrompts = {
  official: [
    "Make the existing card easier for security staff to verify without changing the official identity.",
    "Replace the small logo treatment with a large restrained institutional emblem.",
    "Use the selected brand image as documentary context, but keep the result formal.",
    "Convert this into a portrait-based staff credential for controlled access.",
    "Keep the decorative art, but discipline it so the pass still reads as official.",
    "Remove nonessential member details and leave only verification-critical information.",
    "Clarify status and benefits while preserving an authoritative visual language.",
    "Reformat this as a tall official badge suited to a lanyard.",
    "Convert the current design into a compact official landscape wallet pass.",
    "Add professional contact information while keeping the credential trustworthy.",
    "Strengthen the official brand color across the whole credential.",
    "Quiet the design and use the logo only as a subtle institutional watermark.",
    "Introduce a restrained anti-counterfeit-style pattern without making it decorative.",
    "Move the selected image into a controlled side panel beside the official fields.",
    "Make the QR the first thing a verifier can locate and scan.",
  ],
  minimal: [
    "Simplify the current card into one calm verification hierarchy.",
    "Enlarge the logo into one clean geometric statement and remove competing decoration.",
    "Use one brand photograph as the only visual flourish in an otherwise sparse card.",
    "Turn this into a clean portrait identity card with no unnecessary details.",
    "Reduce the art area to one small, intentional accent.",
    "Remove every field that is not essential to membership verification.",
    "Show tier and points with quiet typography instead of promotional styling.",
    "Convert this into a disciplined vertical badge with a restrained portrait.",
    "Reformat the card as a thin horizontal wallet pass.",
    "Add contact details, but preserve the minimal visual density.",
    "Use the primary color across the card while keeping the composition exceptionally simple.",
    "Replace visible branding with a faint logo watermark.",
    "Turn the loud decoration into a barely visible repeating pattern.",
    "Move the image into one precise panel and simplify everything around it.",
    "Let the QR lead the layout and make all supporting information quieter.",
  ],
  premium: [
    "Elevate the existing card into a concierge-ready premium credential.",
    "Make the logo feel like a large embossed emblem rather than a header mark.",
    "Use the selected image as a cinematic premium backdrop.",
    "Turn this into an editorial portrait membership card.",
    "Refine the artwork area so the card feels like a collectible patron credential.",
    "Remove crowded fields and let spacing create the premium feeling.",
    "Make tier and points the centerpiece of a polished rewards experience.",
    "Convert the design into a tall VIP hospitality badge.",
    "Reformat this as a precision-crafted landscape wallet card.",
    "Add portrait and contact details for a private member network.",
    "Make the official color much more immersive without losing legibility.",
    "Dial back visible effects and rely on a quiet premium watermark.",
    "Replace generic decoration with a bespoke-feeling signature pattern.",
    "Use a refined image panel beside a precise member-benefit hierarchy.",
    "Integrate the QR into the premium composition instead of leaving it as an afterthought.",
  ],
  playful: [
    "Make the current verification experience feel friendlier and more welcoming.",
    "Turn the logo into an oversized playful shape around the member details.",
    "Use the hero image as a bright social backdrop.",
    "Make the member photo feel like a lively community profile.",
    "Add a collectible character or decorative-art area with join date.",
    "Remove the clutter and keep only the friendly essentials.",
    "Present tier and points like visible progress in a game.",
    "Convert this into a lively vertical community badge.",
    "Make it a compact horizontal wallet pass that still feels energetic.",
    "Add photo and contact details for a social member profile.",
    "Push the official color into a joyful full-card treatment.",
    "Tone down the noise and use a soft logo watermark as the playful detail.",
    "Replace the current background with a bold branded wrapping-paper pattern.",
    "Move the bright image into a side panel beside approachable member information.",
    "Make the QR part of the playful rhythm and easier to find.",
  ],
  creative: [
    "Recompose the current card as an art-directed but usable verification credential.",
    "Turn the logo into a giant poster-like graphic.",
    "Use the hero image as the full expressive canvas.",
    "Convert the member identity into an independent-magazine-style portrait layout.",
    "Add a dominant custom-art area and make the card feel collectible.",
    "Remove the excess information and keep the experimental composition sparse.",
    "Turn tier and points into a bold typographic artwork.",
    "Reformat this as a tall limited-edition creative-event badge.",
    "Create an asymmetric horizontal wallet composition.",
    "Add portrait and contact details like a compact portfolio cover.",
    "Use the primary color as a full-bleed expressive field.",
    "Make the card conceptually quieter with a barely visible logo artifact.",
    "Replace generic decoration with a distinctive reusable pattern system.",
    "Create stronger tension between one image panel and the information hierarchy.",
    "Make the QR the visual anchor without making the rest of the card conventional.",
  ],
  cyberpunk: [
    "Optimize the current token for rapid verification in a high-energy digital venue.",
    "Turn the logo into a giant illuminated system emblem.",
    "Replace the background with a high-contrast futuristic hero image.",
    "Make this a portrait identity token with a prominent face and status readout.",
    "Add a collectible digital-character artwork slot.",
    "Strip the token down to critical identity and access data.",
    "Present tier and points like live system statistics.",
    "Convert this into a tall neon lanyard badge.",
    "Reformat it as a compact landscape heads-up-display wallet token.",
    "Add portrait and direct contact channels for a futuristic professional ID.",
    "Flood the pass with official color and sharper contrast.",
    "Replace loud effects with a faint holographic logo watermark.",
    "Introduce a coded repeating pattern that suggests encrypted data.",
    "Move the dramatic image into a panel beside a precise digital readout.",
    "Make scanning the central interaction and enlarge the QR zone.",
  ],
  academic: [
    "Make the current card suitable for library, exam, and campus-building verification.",
    "Turn the university mark into a large heraldic background emblem.",
    "Use a campus image as a formal institutional backdrop.",
    "Add a clear student portrait, student number, course, and expiry.",
    "Turn this into a tasteful alumni or student-society collectible card.",
    "Remove everything not required for campus verification.",
    "Clarify academic status and available benefits.",
    "Convert this into a tall academic conference badge.",
    "Reformat it as a practical landscape student wallet pass.",
    "Add portrait and professional contact details for academic networking.",
    "Strengthen the institutional primary color while keeping formal authority.",
    "Replace the loud branding with a subtle crest-like watermark.",
    "Introduce a scholarly pattern inspired by archive labels or library grids.",
    "Move the campus image into a side panel beside formal student details.",
    "Make the QR dominant for fast controlled entry during exams.",
  ],
  luxury: [
    "Make the existing card feel like a discreet invitation-only credential.",
    "Transform the logo into a monumental embossed-style emblem.",
    "Use the selected image like a luxury editorial campaign backdrop.",
    "Turn the member photo into a private-client portrait treatment.",
    "Refine the artwork area into a carefully framed patron detail.",
    "Remove crowded information and let immaculate spacing carry the design.",
    "Present tier and rewards as discreet privileges.",
    "Convert this into a tall exclusive VIP badge.",
    "Reformat it as a precision-crafted landscape wallet membership.",
    "Rework this as a discreet client introduction card with a photograph and direct communication details.",
    "Use the official color across the full card with tonal depth.",
    "Remove obvious effects and center the card on an almost invisible watermark.",
    "Replace the current pattern with something inspired by engraving or bespoke material.",
    "Move the premium image into a disciplined panel beside member information.",
    "Make the QR elegant, integrated, and immediately scannable.",
  ],
  event: [
    "Optimize the current badge for the fastest possible entry-lane verification.",
    "Turn the event logo into a giant stage-like emblem.",
    "Use the hero image as a full event-poster backdrop.",
    "Add a highly visible attendee photo for staff inspection.",
    "Make this a collectible festival pass with art and attendance date.",
    "Remove every detail that entry staff do not need.",
    "Make sponsor or VIP tier and benefits immediately visible.",
    "Convert this into a tall lanyard badge with photo and contact detail.",
    "Reformat it as a landscape mobile ticket.",
    "Add portrait, email, and phone for conference networking.",
    "Use the event color as an immersive full-card signal.",
    "Quiet the badge and rely on a faint event-logo watermark.",
    "Introduce a rhythmic pattern that connects the whole badge system.",
    "Move the event image into a strong panel beside compact attendee data.",
    "Make the QR dominate the pass for high-volume gate scanning.",
  ],
  identity: [
    "Make the existing card verifiable in a single glance.",
    "Enlarge the logo into a supporting emblem that still keeps the member central.",
    "Place the identity over a cinematic brand-image backdrop while preserving face clarity.",
    "Turn this into a confident portrait-first identity credential.",
    "Add a personal decorative-art slot without weakening identity verification.",
    "Remove all fields except face, name, member ID, expiry, and QR.",
    "Add tier and points while preserving the identity-first hierarchy.",
    "Convert this into a tall wearable identity badge.",
    "Reformat this as a landscape phone-wallet identity pass.",
    "Add email and phone to create a professional member identity credential.",
    "Use the primary color across the full card without reducing portrait clarity.",
    "Replace visible decoration with a quiet logo watermark.",
    "Introduce a branded pattern around a clear central portrait.",
    "Move the image into a side panel beside the organized member portrait.",
    "Balance a larger QR with the member portrait as equal verification tools.",
  ],
};

function scenarioFrom(mood, prompt, index, task) {
  const base = moodProfiles[mood];
  const modifier = intentModifiers[index];
  return {
    key: `${task}-${mood}-${modifier.key}`,
    task,
    mood,
    prompt,
    orientation: modifier.orientation ?? base[0],
    backgroundMode: modifier.backgroundMode ?? base[1],
    colorUsage: modifier.colorUsage ?? base[2],
    preferredAsset: modifier.preferredAsset ?? base[3],
    treatment: modifier.treatment ?? base[4],
    intensity: modifier.intensity ?? base[5],
    usesPhoto: modifier.usesPhoto ?? base[6],
    usesDecorativeArt: modifier.usesDecorativeArt ?? base[7],
    fields: [...new Set([...base[8], ...modifier.fields])],
    removeFields: modifier.removeFields ?? [],
  };
}

function buildTaskScenarios(source, task) {
  return Object.entries(source).flatMap(([mood, prompts]) => {
    if (prompts.length !== intentModifiers.length) {
      throw new Error(`${task}/${mood} must contain exactly ${intentModifiers.length} prompts`);
    }
    return prompts.map((prompt, index) => scenarioFrom(mood, prompt, index, task));
  });
}

export const generationScenarios = buildTaskScenarios(generationPrompts, "generation");
export const refinementScenarios = buildTaskScenarios(refinementPrompts, "refinement");
export const allV4Scenarios = [...generationScenarios, ...refinementScenarios];

if (generationScenarios.length !== 150 || refinementScenarios.length !== 150) {
  throw new Error("The v4 library must contain exactly 150 generation and 150 refinement scenarios.");
}
